Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -26,6 +26,26 @@ jobs:
     - name: Restore dependencies
       run: dotnet restore
     - name: Build
-      run: dotnet build --no-restore
-    - name: Test
-      run: dotnet test --no-build --verbosity normal
+      run: dotnet build --no-restore --logger "trx;LogFileName=test-results.trx"
+      
+    #- name: Test
+    #  run: dotnet test --no-build --verbosity normal
+      
+   # - name: Publish Test Results
+   #   uses: dorny/test-reporter@v1.5.0
+   #   if: success() || failure()
+   #   with: 
+   #     name: Test Result View
+   #     path: 
+    
+    
+    - name: dotnet-tests-report
+      # You may pin to the exact commit or the version.
+      # uses: zyborg/dotnet-tests-report@ce730c068bb73480dcb37c02d40890bf8b44c953
+      uses: zyborg/dotnet-tests-report@v1.4.4
+
+
+
+
+  
+      
